CREATE DATABASE sp_rec;

USE sp_rec; 

CREATE TABLE std_info (ID VARCHAR(50) PRIMARY KEY,F_name VARCHAR(50),L_name VARCHAR(50),Pasword VARCHAR(50),Gender VARCHAR(50),DOB DATE,Contact VARCHAR(50) UNIQUE,Address VARCHAR(50));

CREATE TABLE first_term (FT INT AUTO_INCREMENT PRIMARY KEY,ID VARCHAR(50),S_engineering FLOAT,DBMS FLOAT,O_system FLOAT,N_method FLOAT,S_language FLOAT,FOREIGN KEY(ID) REFERENCES std_info(ID));

CREATE TABLE mid_term (MT INT AUTO_INCREMENT PRIMARY KEY,ID VARCHAR(50),S_engineering FLOAT,DBMS FLOAT,O_system FLOAT,N_method FLOAT,S_language FLOAT,FOREIGN KEY(ID) REFERENCES std_info(ID));

CREATE TABLE pre_board (PB INT AUTO_INCREMENT PRIMARY KEY,ID VARCHAR(50),S_engineering FLOAT,DBMS FLOAT,O_system FLOAT,N_method FLOAT,S_language FLOAT,FOREIGN KEY(ID) REFERENCES std_info(ID));

CREATE TABLE board (BD INT AUTO_INCREMENT PRIMARY KEY,ID VARCHAR(50),S_engineering FLOAT,DBMS FLOAT,O_system FLOAT,N_method FLOAT,S_language FLOAT,FOREIGN KEY(ID) REFERENCES std_info(ID));

CREATE TABLE adm_info (aid INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50),pasword VARCHAR(50));

CREATE TABLE attendance (att_id INT AUTO_INCREMENT,ID VARCHAR(50),start_sem DATE,end_sem DATE,dates DATE,std_status VARCHAR(50),PRIMARY KEY(att_id, ID),FOREIGN KEY(ID) REFERENCES std_info(ID));

, Software Engineering = 55, DBMS = 35, Operating SYSTEM = 38, Numerical Method = 44, Scripting LANGUAGE = 67.